// treetask data — edit this file, refresh index.html (`make tree`).
// PRINCIPLE: every node is an OUTCOME you can check ("the form fills itself"),
// not a mechanism ("ranked arbitration"). Mechanisms live in notes/children.
// Node: { id?, title, status, note?, priority?, deps?: [ids], children? }
//   status:   "done" | "partial" | "next" | "pending" | "risk"
//   priority: integer — shows in the priority table, lower = higher
//   deps:     ids that must be DONE before this can start (⛓ = blocked)
const TREE = {
  id: "root",
  title: "Complete Intern",
  status: "partial",
  note: "An agent that learns GUI work by WATCHING a person do it — then does it alone, their way. No hardcoded rules anywhere. Done = all three proof-scopes pass + thesis written.\n\nWhy it beats the alternatives: scripted RPA breaks on any change and knows no user; generic computer-use agents (incl. Codex Record & Replay) generalize a procedure but clone nobody. Intern's claims: personalization, local execution, judgment cloning.",
  children: [
    {
      id: "scope1",
      title: "1 · The form fills itself",
      status: "partial",
      note: "Proof scope #1 (car-insurance form, 8 tabs). DONE means: all 5 intake records entered and submitted in the demonstrated order, unattended, with numbers to prove it.",
      children: [
        {
          id: "acceptance-run",
          title: "One record, end to end, hands off",
          status: "done",
          deps: ["v3-model", "sections-work", "widgets-fill"],
          note: "THE GATE — PASSED 2026-07-10 evening. One uninterrupted run on v3: tab 0 → all 8 tabs → verify → autonomous Submit, zero human touches, whole week's stack live together. Earlier same-evening attempt wedged in the jump ping-pong (~step 180, Drivers); density gate + viewport lock + far-field reveal landed, rerun submitted. Caveat: metrics block not archived — capture the scorecard on the next run.",
        },
        {
          id: "trust-numbers",
          title: "The score can be trusted",
          status: "partial",
          priority: 2,
          note: "Run scorer (eval_metrics) section-fix 2026-07-10 (41cff4c). bc_fidelity FIXED 2026-07-11: honest rescore of the ×2 run = record 1: 89.3% field / 100% value / 0 mismatches; record 2: 63.5% / 100% (was 20%/32.6% fiction). Remaining children below.",
          children: [
            { id: "bc-record-gold", title: "bc_fidelity grades each record vs ITS OWN answers", status: "done",
              note: "FIXED 2026-07-11: _detect_record_num matches the submission's policy number against each intake record (data-driven), rebuilds gold for that record on the fly; static ref = flagged fallback; report prints which gold was used. Verified: 00441→record 1, 00442→record 2." },
            { id: "bc-section-gold", title: "bc_fidelity gold keys are section-aware", status: "done",
              note: "FIXED 2026-07-11: _parse_intake_record tracks [Section] headers — bare labels inside [Driver N]/[Vehicle 2+] never map to ph_*/v_* keys (Driver 3's 'Tyler' had overwritten ph_first); first-occurrence-wins belt; intake annotations ('← NOTE', '[VERIFY —…]') stripped from gold values." },
            { id: "bc-gold-coverage", title: "BC gold covers the whole form, not 3 tabs", status: "pending",
              note: "_LABEL_TO_KEY maps Policy/Policyholder/Vehicle only (~75 fields) — Drivers/Coverage/Claims/Payment fills are INVISIBLE to the BC score (record 2's claim contamination never showed in it). DO: extend the label→key mapping to all tabs before quoting BC numbers as whole-form fidelity." },
            { id: "eval-record-gold", title: "Run scorer knows which record it's grading", status: "done",
              note: "FIXED 2026-07-11: evaluate_run takes record_num from run_task (which KNOWS which record ran) — no more majority-vote inference mis-picking record 1 (shared generic values + record 1's larger field count biased the vote; ties defaulted to record 1). Inference kept as fallback for callers without the number. Offline-verified against the exact live failure: contamination-biased run scored ✗ 'expected Marcus D. Chen' via inference, ✓ via record_num=2." },
          ],
        },
        {
          id: "sections-work",
          title: "Repeated sections fill correctly (Driver 2/3)",
          status: "done",
          note: "Was: whole sections silently skipped — same-named fields ('First Name' ×3) collided in every skip-list. Fixed 07-09: identities are (section, label); sweep looks up section-correct values. Live-verified on the Drivers tab.",
        },
        {
          id: "widgets-fill",
          title: "Every widget type can be filled",
          status: "partial",
          note: "No more dead fields. Backbone = the identity executor: command controls directly through Windows' accessibility API (set value / toggle / select) instead of clicking coordinates and pasting.",
          children: [
            { id: "identity-core", title: "Direct control API built + proven (edits, spins, checkboxes, combos)", status: "done",
              note: "_act_on_element: ValuePattern/TogglePattern/SelectionItem. Live-verified on Drivers." },
            { id: "identity-everywhere", title: "ALL fill paths use ONE pipeline (pixels last)",
              status: "partial", priority: 4, deps: ["identity-core", "acceptance-run"],
              note: "INVERSION LANDED 2026-07-11 (user-driven: the three bolted-on combobox rescues were a band-aid): new _fill_element = THE fill pipeline — reliable mechanics first (_act_on_element: patterns + keyboard select, read-back verified), legacy pixel/paste LAST. All three combobox paths (click-fill, type-path, reveal-focus) now call it; the three rescue copies and per-site dropdown dances are DELETED. _nav_fill_field already identity-first. OPT2 edit typing keeps its paste→keystroke→pattern-write ladder deliberately (paste is the correct cheap tier for plain edits; spins escalate to pattern write before dead-mark). DRILL PASSED 2026-07-11 22:44: 'State'→'Texas' AND 'DL Issuing State'→'Texas' each in ~1s, one log line, zero rescues/Escapes (the second 50-state widget was never explicitly fixed — the general mechanic covered it); all combobox flavors through the pipeline; 15/15 values, 3.6% waste. REMAINING: full acceptance on this architecture; verify-fix read-back unification; then retire snap/stale-coord guards." },
            { id: "dead-widgets", title: "Stubborn cases: long dropdowns + paste-reject spins", status: "done",
              note: "DONE 2026-07-11, verified three ways: probe (scratch/probe_dead_widgets.py — spin ''→'3' via ValuePattern/RangeValue; 'State' ''→'Texas' below-fold, winner = FIRST-LETTER CYCLING with read-back, wx.Choice matches single chars); drills 22:44 + 23:08 (both 50-state widgets ~1s each, all three combobox paths through the pipeline); spin rescue live 22:49. User caught mid-way that a drill alone wasn't proof AND that rescues-after-pixel-failure were a band-aid — both led to the pipeline inversion. Residual split out → spin-visibility." },
            { id: "spin-visibility", title: "Filled spin values visible to the observer", status: "pending",
              note: "Found 22:49: the identity-executor write LANDS, but the OBSERVED element's value stays '' → model re-targets the already-filled field (~15 wasted steps) → wrongly dead-marked. (23:08 drill: same field took its value first try — intermittent.) DO: read back via the same _resolve_live_control identity the writer used, or mask rescue-filled keys as attempted+filled regardless of observed value." },
          ],
        },
        {
          id: "model-drives",
          title: "The learned model does the driving (LLM < 5%)",
          status: "partial",
          note: "Today the LLM assists ~45-50% of steps. The thesis claim needs the TRAINED policy driving nearly everything; LLM = values only.",
          children: [
            { title: "Navigation: fill batch → jump to densest work → repeat", status: "done",
              note: "Navigation Protocol v2: model's own ranked targets, visible-first; viewport jumps anchored on the model's next pick. Replaced the guard pile.\n\nPing-pong regression (2026-07-10, two anchors alternating 14 jumps / zero fills) fixed same day and CONFIRMED by the passing acceptance run: density gate + viewport lock (no re-jump since last progress) + far-field reveal (focus the window's far-side field — whole window on screen in one SetFocus, no ScrollPattern). Offline probe: scratch/probe_jump_pingpong.py (5/5)." },
            { title: "Model speaks in intents, not raw clicks", status: "done",
              note: "Universal Semantic Action Space: verbs (set-value/toggle/select/…) + split pointer heads. v2 beat baseline 0.957 vs 0.878." },
            { id: "alt-llm", title: "Find alternative LLM", status: "pending",
              note: "Evaluate replacements for LM Studio 'local-model' as the WHAT-provider. Pain: 2-5s/call latency, wrong-line grabs, JSON drift. DO: benchmark candidates (newer Qwen/Llama/Phi locals, or the wired Groq path) on the same prompts — value accuracy vs intake, latency, format reliability. Right-size: the deterministic-lookup fix shrinks how much this matters." },
            { id: "verb-loop", title: "Agent acts on the model's intents directly", status: "pending",
              priority: 3, deps: ["acceptance-run"],
              note: "predict() already outputs verbs; the agent still converts to legacy click/type dicts. Wiring verbs → identity executor is what collapses LLM dependency and retires the remaining navigation crutches.\n\nLLM-45% ATTACK PLAN:\n1. [DONE — LIVE-VERIFIED 23:08 drill] Deterministic value short-circuit: every value 'no LLM call', fields landing ~2s apart (was ~7s), ONE HTTP call in the whole stretch (the GAP tab-advance). Design rule settled with user: look up what's look-up-able, think only about what isn't — LLM's jobs = ambiguity, judgment (Scope 3), rule inference.\n2. [NEXT] Deterministic next-tab — the GAP tab-advance is now the dominant remaining LLM consumer.\n3. Verb-loop (this node) — verbs+pointer straight into the identity executor; makes <5% structural.\nHonest accounting (398d30c): 'LLM Calls (actual HTTP)' metrics line counts ALL calls incl. nav/sweep/verify — the tag-based 0.0% only covered fill-decisions." },
          ],
        },
        {
          id: "good-data",
          title: "Clean demos → faithful model",
          status: "partial",
          note: "The model can only be as orderly as its training data. Sequence fidelity (Behavioral Match) is a thesis metric.",
          children: [
            { id: "v3-model", title: "v3 model on scrubbed demos (footer clicks removed)", status: "done",
              note: "click_acc 0.945, typing-target 0.85. Section-aware 'attempted' feature baked in." },
            { title: "More demos where the model is weakest (deep tabs, rare moves)", status: "pending",
              note: "Project rule: root fix for mis-prediction = more demos, not more guards." },
          ],
        },
        {
          id: "verify-at-fill",
          title: "Verification doesn't re-check what's already confirmed",
          status: "done",
          note: "IMPLEMENTED 2026-07-10, live-exercised in the ×2 probe 2026-07-11: both records ran the gated verify and submitted — no wedge, no missed-fill regression. Mechanism: LLM completeness call fires only when a view shows an EMPTY live fillable the deterministic branch couldn't settle; filled views skip straight to the next scroll. Deterministic clobber-catch + convergence gate unchanged. Caveat: wall-time saving not explicitly measured.",
        },
        {
          id: "five-records",
          title: "Five records in a row",
          status: "partial",
          priority: 5,
          deps: ["acceptance-run", "trust-numbers"],
          note: "The scope's Definition of Done. ×2 probe PASSED 2026-07-11: both records submitted, record 2 filled with record-2 data, reset clean, scorecards archived (record-2 mechanics best yet: 3.7% waste, 1.9 steps/field, 96.3% exec success). Subtasks below = the probe's findings.",
          children: [
            { id: "record-bounds", title: "Blank fields don't inherit record 1's values", status: "done",
              note: "CONFIRMED LIVE 2026-07-11 (second --start_record 2 probe): every claim-field peek returned nothing, cache stayed at record 2's 135 fields, zero record-1 values. Two fix rounds: (1) strict record bound at five blob-parse sites; (2) _record_line_span — all line searches (_peek_notepad, NotepadDataSource.peek/peek_next_after/refresh) bounded to record N's slice, absent record = search NOTHING. LESSON: audits find what you suspect, probes find what you don't." },
            { id: "blank-fills", title: "Absent from record = leave blank (nobody gets to fill it)", status: "partial",
              note: "FOUR fillers, closed one probe at a time: (1) LLM invention on empty lookup → absent=skip, no LLM call — VERIFIED 17:53; (2) merge's TextResolver rescued the empty text from visible Notepad (= record 1) → skip_field flag, resolver not consulted — VERIFIED 18:00; (3) the SWEEP typed LLM junk literally via identity executor → sweep guard: RECORD IS SOURCE OF TRUTH — no record value = stays blank (settled); record value present = beats the LLM proposal. NO literal blacklist (user-flagged: ruleset-inference territory); (4) verify inherits via dead-key exclusion. 18:24 probe: skip machinery PASSED wholesale (every absent field skipped+honored, zero junk, LLM% 16.7%); sweep guard itself unexercised (OPT2 skips settled the tab before sweep fired — same lookup logic, low risk, watched naturally next full run). Residuals: model re-picks skipped fields until STUCK (cheap); annotated blanks ('(N/A — no collision coverage)') typed literally = ruleset-inference case, filed there." },
            { id: "run-x5", title: "The full ×5 run, scorecards archived", status: "pending",
              deps: ["record-bounds", "trust-numbers"],
              note: "DO: --records 5 after record-bounds + scorer fixes; archive all 5 scorecards — these are the thesis numbers." },
          ],
        },
        {
          id: "self-improving",
          title: "It learns its own rules from runs",
          status: "pending",
          priority: 6,
          note: "Ruleset-inference loop is OPEN: inferred rules (e.g. 'leave blank means skip') never reach the LLM. Close extract() → ruleset.md → prompt. Fresh case (2026-07-11): 'Deductible ($)' typed the literal '(N/A — no collision coverage)' straight from the record — 'n/a + annotation = leave empty' is a learnable rule, deliberately NOT hardcoded.",
        },
      ],
    },
    {
      id: "vision",
      title: "It can see (pixels, not APIs)",
      status: "partial",
      note: "Big Three #1 — CV+OCR observer (PR #8): screenshot → boxes + text → same element schema. Proven: agent NAVIGATES from pixels (2026-07-10 probe, 7/7 on-target clicks); tooling: per-observation flipbook + live viewer (make see). Not yet: filling. This is the generalization organ — Scope #2+ needs it; Scope #1 stays on UIA.",
      children: [
        { id: "vision-focus", title: "It knows which field it's in (focus inference)", status: "risk",
          note: "THE BLOCKER: pixels expose no keyboard focus → the fill trigger ('focused empty field') never fires → navigates forever, types nothing (live-observed). DO: agent-side inferred focus = last clicked fillable when observer reports None; later, visual caret detection." },
        { id: "vision-labels", title: "It reads labels whole, not in pieces", status: "done",
          note: "FIXED (424beea): whole-line assembly via Tesseract line ids + punctuation cleanup — all 10 Tab-1 labels whole/exact; identity-executor fills landed on clean labels. Residual: label/value bleed on filled fields (goes away with the learned parser)." },
        { id: "vision-identity", title: "It knows a field is the SAME field across frames", status: "done",
          note: "FIXED (819a4a7): detector ids were per-frame detection order — consecutive frames named different fields with the same id, so fills were verified against the WRONG element and dead-marked. Frame-to-frame tracker (label + nearest center) carries ids; parser-agnostic. Unit-verified; needs one live probe to confirm read-back." },
        { title: "It ignores window chrome", status: "pending",
          note: "Caption-bar buttons detected as checkboxes — the agent clicked 2px from CLOSE. DO: exclude the captured window's title-bar band from detection (by caption height, not pixels)." },
        { title: "It tells dropdowns from text fields", status: "pending",
          note: "0 comboboxes detected on a tab with 3 → wrong fill mechanics chosen. DO: detect the dropdown arrow glyph at the right edge of the box." },
        { id: "alt-vlm", title: "Find alternative VLM", status: "pending",
          note: "Evaluate vision-language / screen-parsing models for the perception seam. Candidates: OmniParser v2, ShowUI, UGround, Qwen2.5-VL — local preferred (human-like control rule). DO: benchmark each behind the same detect_elements() seam; accept when perception_eval beats the current classical baseline on box precision/recall + label accuracy. Overlaps vision-parser — this is the model-selection half." },
        { id: "vision-parser", title: "Real fix: learned screen parser replaces hand-rolled CV", status: "pending",
          note: "The classical detector needs a new heuristic per widget style — it will never generalize (guard-pile anti-pattern, perception edition). DO: swap cv_detector's core for a pretrained screen-parsing model (OmniParser-class, local ONNX; evaluate ShowUI/UGround) behind the SAME detect_elements() seam; keep Tesseract for values; accept when perception_eval beats the classical baseline on precision/recall + label accuracy." },
        { title: "Vision demos recorded + vision model trained", status: "pending",
          deps: ["vision-focus", "vision-labels"],
          note: "DO (after the two blockers): record with --perception vision, clean, train — the model that needs no accessibility tree at all." },
      ],
    },
    {
      id: "scope2",
      title: "2 · It moves data between apps",
      status: "pending",
      deps: ["acceptance-run", "five-records", "vision"],
      note: "Proof scope #2: web form → Excel. Same engine, different eyes and hands. Perception swap already PROVEN (ExcelObserver speaks the same schema).",
      children: [
        { title: "Excel eyes: read live sheets reliably", status: "partial",
          note: "DO: run ExcelObserver against real workbooks; verify cell text, formulas, coordinates and sheet names land in the canonical element schema. The swap was proven once in isolation (2026-06-09) — needs endurance testing, not design." },
        { title: "Excel hands: target cells, enter values", status: "pending",
          note: "DO: implement cell targeting (click or arrow-key navigation to the active cell) + value entry, as identity-executor-style actions. Decide click-per-cell vs keyboard navigation by recording how the human actually does it." },
        { title: "15-20 recorded transfer demos", status: "pending",
          note: "DO: record with app/main.py — one pass = read a web-form record, enter it into the Excel template. Same recorder, new out_dir (e.g. data/demos/excel_transfer). NO duplicate button; clean with clean_demos.py after." },
        { title: "Trained + fidelity measured", status: "pending",
          note: "DO: train a task-specific checkpoint on the transfer demos (make train-semantic TRACE_DIR=...), then a live run scored against the source records. Pass = same bar as Scope #1: unattended, correct values, demonstrated order." },
      ],
    },
    {
      id: "scope3",
      title: "3 · It clones judgment, not just steps",
      status: "pending",
      deps: ["scope2"],
      note: "Proof scope #3: email/ticket triage — two users triage DIFFERENTLY, and the agent reproduces its user's calls. The claim no record-and-replay tool can make.",
      children: [
        { title: "Demos with decisions in them (varied inputs → varied responses)", status: "pending",
          note: "DO: design + record a triage task where the INPUT varies and the demonstrated RESPONSE varies with it (e.g. active policy → reply A, lapsed → warning, missing fields → inquiry). Keep every decision inferable from VISIBLE content — no hidden intent. This dataset design is the hard part; do it before any code." },
        { title: "Learn the branching (what condition drives which action)", status: "pending",
          note: "DO: build the workflow-induction pass — compare traces across cases, find the state features that predict which action branch was taken, emit an explicit branching spec (JSON/MD). Then measure: does the trained agent take the USER'S branch on held-out cases?" },
        { id: "dagger", title: "Learn from corrections (DAgger)", status: "risk",
          note: "CorrectionHandler currently captures 0 steps in live runs — the correction loop is wired but dead. Blocks cold-start improvement." },
      ],
    },
    {
      id: "thesis",
      title: "4 · The proof is written down",
      status: "pending",
      note: "The academic deliverable: the three scopes turned into chapters, metrics and benchmark comparisons. Nothing here starts producing text until Scope #1 has trustworthy numbers.",
      children: [
        { title: "Methodology + evaluation chapters", status: "pending", deps: ["scope1"],
          note: "DO: write thesis ch.3 (architecture: perception adapter → transformer WHERE → LLM WHAT → identity-executor HOW; BC training recipe) and ch.4 (metrics + runs). Blocked on Scope #1 numbers being real — which needs the trusted scorer first." },
        { title: "Benchmarks vs generic agents (OS-World)", status: "pending",
          note: "DO: pick 2-3 comparable form/transfer tasks from OS-World (or equivalent), run a generic agent and Intern on both, compare completion + fidelity + cost-per-run. The claim to support: personalization + local execution beat generic agents on repeated personal workflows." },
        { id: "behavioral-match", title: "Sequence-fidelity metric actually measures", status: "partial",
          note: "FIXED 2026-07-12 (offline-verified): reference was pointed at a DEAD dir → 'No reference sequence available' → 0% forever. Now: reference = the training corpus (data/demos/eight_Tabs_clean2, BC_TRACES_DIR overridable), extractor handles the demo-recorder format (per-keystroke traces collapsed to per-field), cached (134s build → 0.02s hit). CALIBRATION: demo-vs-demo similarity = 81% — the human consistency ceiling; a perfect clone scores ~80%, not 100%. Report agent scores against that baseline. DO: first live number comes free with the next run's BC block." },
      ],
    },
  ],
};
